[tool.poetry]
name = "day_29"
version = "0.1.0"
description = ""
authors = ["Javier GonzaÌlez Rojo <bigjagonza2000@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
